monitor:
  devid: HR010
  devname: Nanopi冷却水水温
  feedbacktopic: cmd/feedback
  interval: 120
  isopen: true
  pubtopic: eim/monitor
mqtt:
  clientid: hpuwatertemp01
  host: 127.0.0.1
  keepalive: 60
  port: 1883
tcpmodbus:
  hpu:
    addrcode: 1
    datalen: 50
    devname: HPU001
    interval: 4
    iplist:
    - 192.168.100.1
    location: A2
    maptable:
    - datalen: 1
      name: temperature
      startaddr: 431
    - datalen: 1
      name: flow
      startaddr: 433
    - datalen: 1
      name: pressure
      startaddr: 434
    - datalen: 1
      name: pumps_running_num
      startaddr: 437
    - datalen: 1
      name: pumps_total_num
      startaddr: 438
    - datalen: 2
      name: pump_total_running_time
      startaddr: 440
    - datalen: 2
      name: pump1_running_time
      startaddr: 442
    - datalen: 2
      name: pump2_running_time
      startaddr: 444
    - datalen: 2
      name: pump3_running_time
      startaddr: 446
    - datalen: 2
      name: pump4_running_time
      startaddr: 448
    - datalen: 2
      name: pump5_running_time
      startaddr: 450
    - datalen: 2
      name: pump6_running_time
      startaddr: 452
    - datalen: 2
      name: pump_total_running_time2
      startaddr: 456
    - datalen: 6
      name: pump1_6_status
      startaddr: 462
    - datalen: 6
      name: pump1_6_status_model
      startaddr: 468
    - datalen: 1
      name: pump_total_status
      startaddr: 474
    method: tcp
    port: 502
    pubtopic: sensor/hpu/plc
    sid: hpu001
    startaddr: 430
    unit: 
     - 1
uartmodbus:
  noise:
    baudrate: 9600
    devname: 噪声北
    holdingreg:
      addrcode: 1
      datalen: 1
      startaddr: 0
    interval: 6
    location: A1
    method: rtu
    port: COM3
    pubtopic: sensor/noise
    sid: noise001
    timeout: 1
    units: 
      - 1
  pressure:
    baudrate: 9600
    devname: 压力001
    holdingreg:
      datalen: 1
      startaddr: 1
    interval: 1
    location: A1
    method: rtu
    port: COM5
    pubtopic: sensor/hpu/waterpressure
    sid: pressure001
    timeout: 1
    units: 
      - 1
    waterpremax: 1.6
    waterpremin: 0
  pt100:
    baudrate: 9600
    damexpand: 1.2
    damrange: 20
    devname: 油泵间冷却水水温
    holdingreg:
      datalen: 12
      startaddr: 2
    interval: 1
    location: HPU油泵间
    mappedvalue: 0.32
    method: rtu
    minma: 4
    port: COM3
    pubtopic: sensor/hpu/watertemp
    sid: pt100
    timeout: 1
    units: 
      - 1
  ampere: #电流
    baudrate: 9600
    damexpand: 1.2
    damrange: 20
    devname: 油泵间电流
    holdingreg:
      datalen: 1
      startaddr: 2
    interval: 2
    location: HPU油泵间
    mappedvalue: 0.16
    method: rtu
    minma: 4
    port: COM3
    pubtopic: sensor/hpu/ampere
    sid: ampere001
    timeout: 1
    units:
     - 1
     - 2
  temphumi:
    baudrate: 9600
    devname: 温湿度传感器
    holdingreg:
      datalen: 2
      startaddr: 0
    interval: 20
    location: HR009
    method: rtu
    port: /dev/ttyUSB0
    pubtopic: sensor/weather
    sid: weather001
    timeout: 1
    units: 
      - 1
